### ISSUE TITLE
How to create credentials.sh file

### ISSUE THREAD

**Issue by Dievale** [ignaciohermosillacornejo/Asuswrt-Merlin-Scripts#1]
Hi Thanks for your script. Could you please tell me how can I create the file credentials.sh? Im Putty connected to my router and I have a pushover account but I don't know how to create credentials.sh file via ssh.
You said "After installing the App on your smartphone, SSH in your router and create the file /jffs/scripts/credentials.sh with the following content:

#!/bin/sh

export pushover_token="<Your pushover token goes here>"
export pushover_user="<Your pushover user goes here>"

**Comment by ignaciohermosillacornejo** [comment]
Hi @Dievale 

You could learn to use [nano](https://www.howtogeek.com/howto/42980/the-beginners-guide-to-nano-the-linux-command-line-text-editor/) if you want to start tinkering with files via the terminal, how ever if you're justlooking to get the notifications up and running fast try running these three commands, one after the other:

- `echo '#!/bin/sh' >> /jffs/scripts/credentials.sh`
- `echo 'export pushover_token="<Your pushover token goes here>"' >> /jffs/scripts/credentials.sh`
- `echo 'export pushover_user="<Your pushover user goes here>"' >>  /jffs/scripts/credentials.sh`

Remember to replace `<Your pushover user goes here>` and `<Your pushover token goes here>` with your corresponding  token and user info.

**Comment by Dievale** [comment]
Gracias amigo. I'm getting this errors after running **/usr/sbin/curl --retry 3 "https://raw.githubusercontent.com/ignaciohermosillacornejo/Asuswrt-Merlin-Scripts/master/update-notification" -o "/jffs/scripts/update-notification" && chmod 755 /jffs/scripts/update-notification && sh /jffs/scripts/update-notification**

-sh: {token:invalid,errors:[application token is invalid],status:0,request:a9ce0908-c7fe-43ef-8118-a1acae64ba7b}diego@Router:/tmp/home/root#: not found

I confirmed that pushover token and user are correct

**Comment by ignaciohermosillacornejo** [comment]
Make sure that the token and user are encased in quotes (`"`)

`credentials.sh` file should look something like this:

```
#!/bin/sh

export pushover_token="asdfasdfasdfadsfadsfadf"
export pushover_user="sdfasdfasdfasdfadsfadf"
```

you can manualy test that your credentials are correct, run:
`. /jffs/scripts/credentials.sh` followed by `echo $pushover_token` and you should see your token. If you see it then that means you have some trouble with your pushover token or plan.

As for the code and commands in the instructions, I just retested them and can confirm that they are working.

**Comment by Dievale** [comment]
Thank you. Everything is working now. For user I was using my email instead of the API token.

**Comment by Dievale** [comment]
I mean for user I was using my email instead of user key, and in token I was using my key instead. All good now Gracias!!

**Comment by ignaciohermosillacornejo** [comment]
De nada! If you felt like this repo was of any help please free feel to star it, it really helps with the visibility

**Comment by Dievale** [comment]
Done. Closing the issue
